# version format
version: 1.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
install:
  - cmd: npm install
  - cmd: set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=
  - cmd: set UMBRACO_PACKAGE_MIN_VERSION=7.3.0
  - cmd: Build.cmd

# to disable automatic builds
build: off

artifacts:
  - path: Build\pkg\nuget\*.nupkg
You can do a lot of build configuration using the 